SET IDENTITY_INSERT [Time].[DayNames] ON
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (1, N'Sunday', N'Sun', 0, N'S', N'Su', 0, N'Weekend')
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (2, N'Monday', N'Mon', 1, N'M', N'Mo', 1, N'Weekday')
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (3, N'Tuesday', N'Tue', 2, N'T', N'Tu', 1, N'Weekday')
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (4, N'Wednesday', N'Wed', 3, N'W', N'We', 1, N'Weekday')
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (5, N'Thursday', N'Thur', 4, N'T', N'Th', 1, N'Weekday')
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (6, N'Friday', N'Fri', 5, N'F', N'Fr', 1, N'Weekday')
INSERT [Time].[DayNames] ([DayNameID], [DayName], [DayShortName], [DaySortOrder], [DayAbbreviation], [DayLongAbbreviation], [DayIsBusinessDay], [DayBusinessDayClassification]) VALUES (7, N'Saturday', N'Sat', 6, N'S', N'Sa', 0, N'Weekend')
SET IDENTITY_INSERT [Time].[DayNames] OFF
SET IDENTITY_INSERT [Time].[MonthOfYear] ON
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (1, 0, N'January', N'Jan', N'J')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (2, 1, N'February', N'Feb', N'F')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (3, 2, N'March', N'Mar', N'M')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (4, 3, N'April', N'Apr', N'A')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (5, 4, N'May', N'May', N'M')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (6, 5, N'June', N'Jun', N'J')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (7, 6, N'July', N'Jul', N'J')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (8, 7, N'August', N'Aug', N'A')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (9, 8, N'September', N'Sep', N'S')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (10, 9, N'October', N'Oct', N'O')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (11, 10, N'November', N'Nov', N'N')
INSERT [Time].[MonthOfYear] ([MonthOfYearID], [MonthInYearNumber], [MonthOfYearName], [MonthOfYearShortName], [MonthOfYearAbbreviation]) VALUES (12, 11, N'December', N'Dec', N'D')
SET IDENTITY_INSERT [Time].[MonthOfYear] OFF
SET IDENTITY_INSERT [Time].[PublicHolidays] ON
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (1, 20140101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (2, 20140320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (3, 20140321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (4, 20140418, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (5, 20140419, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (6, 20140420, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (7, 20140421, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (8, 20140427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (9, 20140428, N'Freedom Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (10, 20140501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (11, 20140507, N'Voting Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (12, 20140511, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (13, 20140615, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (14, 20140616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (15, 20140621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (16, 20140809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (17, 20140923, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (18, 20140924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (19, 20141216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (20, 20141221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (21, 20141224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (22, 20141225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (23, 20141226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (24, 20141231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (25, 20130101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (26, 20130320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (27, 20130321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (28, 20130329, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (29, 20130330, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (30, 20130331, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (31, 20130401, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (32, 20130427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (33, 20130501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (34, 20130512, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (35, 20130616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (37, 20130617, N'Youth Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (38, 20130621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (39, 20130809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (40, 20130922, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (41, 20130924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (42, 20131216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (43, 20131221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (44, 20131224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (45, 20131225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (46, 20131226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (47, 20131231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (48, 20120101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (49, 20120102, N'New Year''s Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (50, 20120320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (51, 20120321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (52, 20120406, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (53, 20120407, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (54, 20120408, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (55, 20120409, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (56, 20120427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (57, 20120501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (58, 20120513, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (59, 20120616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (60, 20120617, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (61, 20120620, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (62, 20120809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (63, 20120922, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (64, 20120924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (65, 20121216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (66, 20121217, N'Day of Reconciliation observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (67, 20121221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (68, 20121224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (69, 20121225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (70, 20121226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (71, 20121231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (72, 20110101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (73, 20110320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (74, 20110321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (75, 20110422, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (76, 20110423, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (77, 20110424, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (78, 20110425, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (79, 20110426, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (80, 20110427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (81, 20110501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (82, 20110502, N'Workers'' Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (83, 20110508, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (84, 20110518, N'Election Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (85, 20110616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (86, 20110617, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (87, 20110619, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (88, 20110621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (89, 20110808, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (90, 20110809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (91, 20110923, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (92, 20110924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (93, 20111216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (94, 20111222, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (95, 20111224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (96, 20111225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (97, 20111226, N'Boxing Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (99, 20111227, N'Public holiday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (100, 20111231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (101, 20100101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (102, 20100320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (103, 20100321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (104, 20100322, N'Human Rights Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (105, 20100402, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (106, 20100403, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (107, 20100404, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (108, 20100405, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (109, 20100427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (110, 20100501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (111, 20100509, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (112, 20100615, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (113, 20100616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (114, 20100620, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (115, 20100621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (116, 20100809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (117, 20100923, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (118, 20100924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (119, 20101216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (120, 20101221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (121, 20101224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (122, 20101225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (123, 20101226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (124, 20101227, N'Day of odwill observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (125, 20101231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (126, 20090101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (127, 20090320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (128, 20090321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (129, 20090410, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (130, 20090411, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (131, 20090412, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (132, 20090413, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (133, 20090427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (134, 20090501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (135, 20090615, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (136, 20090616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (137, 20090621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (138, 20090809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (139, 20090810, N'National Women''s Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (140, 20090922, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (141, 20090924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (142, 20091216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (143, 20091221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (144, 20091224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (145, 20091225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (146, 20091226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (147, 20091231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (148, 20080101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (149, 20080320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (150, 20080321, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (151, 20080322, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (152, 20080323, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (153, 20080324, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (154, 20080427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (155, 20080428, N'Freedom Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (156, 20080501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (157, 20080502, N'Bridge Public holiday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (158, 20080615, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (159, 20080616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (161, 20080620, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (162, 20080809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (163, 20080922, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (164, 20080924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (165, 20081216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (166, 20081221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (167, 20081224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (168, 20081225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (169, 20081226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (170, 20081231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (171, 20070101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (172, 20070321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (174, 20070406, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (175, 20070407, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (176, 20070408, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (177, 20070409, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (178, 20070427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (179, 20070501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (180, 20070615, N'School holiday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (181, 20070616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (182, 20070621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (183, 20070809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (184, 20070923, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (185, 20070924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (186, 20071216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (187, 20071217, N'Day of Reconciliation observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (188, 20071222, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (189, 20071224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (190, 20071225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (191, 20071226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (192, 20071231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (193, 20150101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (194, 20150320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (195, 20150321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (196, 20150403, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (197, 20150404, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (198, 20150405, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (199, 20150406, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (200, 20150427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (201, 20150501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (202, 20150510, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (203, 20150616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (204, 20150621, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (206, 20150809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (207, 20150810, N'National Women''s Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (208, 20150923, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (209, 20150924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (210, 20151216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (211, 20151222, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (212, 20151224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (213, 20151225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (214, 20151226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (215, 20151231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (216, 20160101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (217, 20160320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (218, 20160321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (219, 20160325, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (220, 20160326, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (221, 20160327, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (222, 20160328, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (223, 20160427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (224, 20160501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (225, 20160502, N'Workers'' Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (226, 20160508, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (227, 20160616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (228, 20160619, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (229, 20160620, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (230, 20160809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (231, 20160922, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (232, 20160924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (233, 20161216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (234, 20161221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (235, 20161224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (236, 20161225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (237, 20161226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (239, 20161231, N'New Year''s Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (240, 20170101, N'New Year''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (241, 20170102, N'New Year''s Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (242, 20170320, N'March equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (243, 20170321, N'Human Rights Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (244, 20170414, N'od Friday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (245, 20170415, N'Holy Saturday', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (246, 20170416, N'Easter Sunday', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (247, 20170417, N'Family Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (248, 20170427, N'Freedom Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (249, 20170501, N'Workers'' Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (250, 20170514, N'Mother''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (251, 20170616, N'Youth Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (252, 20170618, N'Father''s Day', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (253, 20170621, N'June Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (254, 20170809, N'National Women''s Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (255, 20170922, N'September equinox', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (256, 20170924, N'Heritage Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (257, 20170925, N'Heritage Day observed', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (258, 20171216, N'Day of Reconciliation', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (259, 20171221, N'December Solstice', N'Season')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (260, 20171224, N'Christmas Eve', N'Observance')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (261, 20171225, N'Christmas Day', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (262, 20171226, N'Day of odwill', N'Public Holiday')
INSERT [Time].[PublicHolidays] ([PublicHolidayID], [DayID], [PublicHolidayName], [PublicHolidayType]) VALUES (263, 20171231, N'New Year''s Eve', N'Observance')

SET IDENTITY_INSERT [Time].[PublicHolidays] OFF
