package com.guicedee.activitymaster.core.db.entities.classifications.builders;

import com.guicedee.activitymaster.client.services.builders.warehouse.classifications.IClassificationDataConceptQueryBuilder;
import com.guicedee.activitymaster.core.db.abstraction.builders.assists.QueryBuilderSCDNameDescription;
import com.guicedee.activitymaster.core.db.entities.classifications.ClassificationDataConcept;

public class ClassificationDataConceptQueryBuilder
		extends QueryBuilderSCDNameDescription<ClassificationDataConceptQueryBuilder, ClassificationDataConcept, java.util.UUID>
		implements IClassificationDataConceptQueryBuilder<ClassificationDataConceptQueryBuilder,ClassificationDataConcept>
{
}
