package com.armineasy.activitymaster.activitymaster.db.entities.classifications.builders;

import com.armineasy.activitymaster.activitymaster.db.abstraction.builders.QueryBuilderSecurities;
import com.armineasy.activitymaster.activitymaster.db.entities.classifications.ClassificationDataConceptXClassificationSecurityToken;
import com.armineasy.activitymaster.activitymaster.db.entities.classifications.ClassificationDataConceptXClassificationSecurityToken_;

import javax.persistence.metamodel.Attribute;

public class ClassificationDataConceptXClassificationSecurityTokenQueryBuilder
		extends QueryBuilderSecurities<ClassificationDataConceptXClassificationSecurityTokenQueryBuilder, ClassificationDataConceptXClassificationSecurityToken, Long>
{
	@Override
	protected Attribute getMyAttribute()
	{
		return ClassificationDataConceptXClassificationSecurityToken_.base;
	}
}
